// Fetch Basic Info about User
export const FETCH_USER_BASIC_INFO_REQUEST_TRIGGERED = 'FETCH_USER_BASIC_INFO_REQUEST_TRIGGERED';
export const FETCH_USER_BASIC_INFO_REQUEST_SUCCESS = 'FETCH_USER_BASIC_INFO_REQUEST_SUCCESS';
export const FETCH_USER_BASIC_INFO_REQUEST_FAILURE = 'FETCH_USER_BASIC_INFO_REQUEST_FAILURE';

// Fetch All Projects
export const FETCH_ALL_PROJECTS_REQUEST_TRIGGERED = 'FETCH_ALL_PROJECTS_REQUEST_TRIGGERED';
export const FETCH_ALL_PROJECTS_REQUEST_SUCCESS = 'FETCH_ALL_PROJECTS_REQUEST_SUCCESS';
export const FETCH_ALL_PROJECTS_REQUEST_FAILURE = 'FETCH_ALL_PROJECTS_REQUEST_FAILURE';

// Fetch Project
export const FETCH_PROJECT_REQUEST_TRIGGERED = 'FETCH_PROJECT_REQUEST_TRIGGERED';
export const FETCH_PROJECT_REQUEST_SUCCESS = 'FETCH_PROJECT_REQUEST_SUCCESS';
export const FETCH_PROJECT_REQUEST_FAILURE = 'FETCH_PROJECT_REQUEST_FAILURE';

// Create Project
export const CREATE_PROJECT_REQUEST_TRIGGERED = 'CREATE_PROJECT_REQUEST_TRIGGERED';
export const CREATE_PROJECT_REQUEST_SUCCESS = 'CREATE_PROJECT_REQUEST_SUCCESS';
export const CREATE_PROJECT_REQUEST_FAILURE = 'CREATE_PROJECT_REQUEST_FAILURE';

// Delete Project
export const DELETE_PROJECT_REQUEST_TRIGGERED = 'DELETE_PROJECT_REQUEST_TRIGGERED';
export const DELETE_PROJECT_REQUEST_SUCCESS = 'DELETE_PROJECT_REQUEST_SUCCESS';
export const DELETE_PROJECT_REQUEST_FAILURE = 'DELETE_PROJECT_REQUEST_FAILURE';

// Fetch Project Logs
export const FETCH_PROJECT_LOGS_REQUEST_TRIGGERED = 'FETCH_PROJECT_LOGS_REQUEST_TRIGGERED';
export const FETCH_PROJECT_LOGS_REQUEST_SUCCESS = 'FETCH_PROJECT_LOGS_REQUEST_SUCCESS';
export const FETCH_PROJECT_LOGS_REQUEST_FAILURE = 'FETCH_PROJECT_LOGS_REQUEST_FAILURE';

// Clear Current Project
export const CLEAR_CURRENT_PROEJCT = 'CLEAR_CURRENT_PROEJCT';

// Start Log
export const START_LOG_REQUEST_TRIGGERED = 'START_LOG_REQUEST_TRIGGERED';
export const START_LOG_REQUEST_SUCCESS = 'START_LOG_REQUEST_SUCCESS';
export const START_LOG_REQUEST_FAILURE = 'START_LOG_REQUEST_FAILURE';

// Stop Log
export const STOP_LOG_REQUEST_TRIGGERED = 'STOP_LOG_REQUEST_TRIGGERED';
export const STOP_LOG_REQUEST_SUCCESS = 'STOP_LOG_REQUEST_SUCCESS';
export const STOP_LOG_REQUEST_FAILURE = 'STOP_LOG_REQUEST_FAILURE';

// Delete Log
export const DELETE_LOG_REQUEST_TRIGGERED = 'DELETE_LOG_REQUEST_TRIGGERED';
export const DELETE_LOG_REQUEST_SUCCESS = 'DELETE_LOG_REQUEST_SUCCESS';
export const DELETE_LOG_REQUEST_FAILURE = 'DELETE_LOG_REQUEST_FAILURE';

// Fetch Current Log
export const FETCH_CURRENT_LOG_REQUEST_TRIGGERED = 'FETCH_CURRENT_LOG_REQUEST_TRIGGERED';
export const FETCH_CURRENT_LOG_REQUEST_SUCCESS = 'FETCH_CURRENT_LOG_REQUEST_SUCCESS';
export const FETCH_CURRENT_LOG_REQUEST_FAILURE = 'FETCH_CURRENT_LOG_REQUEST_FAILURE';
